const mongoose = require('mongoose');

const ScheduleSchema = new mongoose.Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    dayOfWeek: [{ type: String, enum: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], required: true }],
    exercises: [{ name: String, sets: Number, reps: Number }],
    autoGenerated: { type: Boolean, default: false }
});

module.exports = mongoose.model('Schedule', ScheduleSchema);