exports.generateWorkoutPlan = (date, userId) => {
    const muscleGroups = [
        { day: 'Monday', exercises: [{ name: 'Bench Press', sets: 3, reps: 12 }, { name: 'Push-ups', sets: 3, reps: 15 }] },
        { day: 'Wednesday', exercises: [{ name: 'Squats', sets: 3, reps: 10 }, { name: 'Lunges', sets: 3, reps: 12 }] },
        { day: 'Friday', exercises: [{ name: 'Deadlifts', sets: 3, reps: 8 }, { name: 'Pull-ups', sets: 3, reps: 10 }] }
    ];

    const dayOfWeek = new Date(date).toLocaleString('en-us', { weekday: 'long' });
    const plan = muscleGroups.find(group => group.day === dayOfWeek);

    if (plan) {
        return {
            userId,
            date,
            exercises: plan.exercises,
            autoGenerated: true
        };
    }
    return null;
};